Migration to GHA
newrelic/nri-rabbitmq pull request #55
Opened 2020-10-16 15:41 UTC by jportasa

2020-11-13 19:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/nri-rabbitmq?pullRequest=55) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/nri-rabbitmq?pullRequest=55) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: brushknight<br/>:x: Joan Porta<br/><hr/>**Joan Porta** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/nri-rabbitmq?pullRequest=55) it.</sub>

2021-01-20 12:56 UTC, roobre requested changes

2021-01-20 12:56 UTC, roobre commented on build/.goreleaser.yml
> +      "rabbitmq-definition.yml": "/var/db/newrelic-infra/newrelic-integrations/rabbitmq-definition.yml"
Missing change to `contents`

2021-01-20 12:56 UTC, roobre commented on build/.goreleaser.yml
> +      "rabbitmq-definition.yml": "/var/db/newrelic-infra/newrelic-integrations/rabbitmq-definition.yml"
Idem

2021-01-21 08:49 UTC, gsanchezgavier approved these changes
lgtm, i check some of the tarball and bin and conifgs looks ok

2021-01-21 10:58 UTC, roobre approved these changes

2021-01-21 12:00 UTC, merged